In [12]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

ImportError: DLL load failed: The specified module could not be found.

In [3]:
data = pd.read_csv(r'G:\my video lecture\projects\italy_covid19.csv')

FileNotFoundError: [Errno 2] File G:\my video lecture\projects\italy_covid19.csv does not exist: 'G:\\my video lecture\\projects\\italy_covid19.csv'

In [4]:
data = pd.read_csv(r'G:\my video lecture\projects\covid19_italy.csv')

In [5]:
data

,SNo,Date,Country,RegionCode,RegionName,ProvinceCode,ProvinceName,ProvinceAbbreviation,Latitude,Longitude,TotalPositiveCases
0,0,2020-02-24T18:00:00,ITA,13,Abruzzo,66,L'Aquila,AQ,42.351222,13.398438,0
1,1,2020-02-24T18:00:00,ITA,13,Abruzzo,67,Teramo,TE,42.658918,13.704400,0
2,2,2020-02-24T18:00:00,ITA,13,Abruzzo,68,Pescara,PE,42.464584,14.213648,0
3,3,2020-02-24T18:00:00,ITA,13,Abruzzo,69,Chieti,CH,42.351032,14.167546,0
4,4,2020-02-24T18:00:00,ITA,13,Abruzzo,979,In fase di definizione/aggiornamento,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...
22912,22912,2020-08-12T17:00:00,ITA,5,Veneto,27,Venezia,VE,45.434905,12.338452,2969
22913,22913,2020-08-12T17:00:00,ITA,5,Veneto,28,Padova,PD,45.406930,11.876087,4383
22914,22914,2020-08-12T17:00:00,ITA,5,Veneto,29,Rovigo,RO,45.071073,11.790070,476
22915,22915,2020-08-12T17:00:00,ITA,5,Veneto,899,Fuori Regione / Provincia Autonoma,NaN,NaN,NaN,316
22916,22916,2020-08-12T17:00:00,ITA,5,Veneto,999,In fase di definizione/aggiornamento,NaN,NaN,NaN,41

In [6]:
data.head()

,SNo,Date,Country,RegionCode,RegionName,ProvinceCode,ProvinceName,ProvinceAbbreviation,Latitude,Longitude,TotalPositiveCases
0,0,2020-02-24T18:00:00,ITA,13,Abruzzo,66,L'Aquila,AQ,42.351222,13.398438,0
1,1,2020-02-24T18:00:00,ITA,13,Abruzzo,67,Teramo,TE,42.658918,13.704400,0
2,2,2020-02-24T18:00:00,ITA,13,Abruzzo,68,Pescara,PE,42.464584,14.213648,0
3,3,2020-02-24T18:00:00,ITA,13,Abruzzo,69,Chieti,CH,42.351032,14.167546,0
4,4,2020-02-24T18:00:00,ITA,13,Abruzzo,979,In fase di definizione/aggiornamento,NaN,NaN,NaN,0

In [7]:
data.columns

Index(['SNo', 'Date', 'Country', 'RegionCode', 'RegionName', 'ProvinceCode',
       'ProvinceName', 'ProvinceAbbreviation', 'Latitude', 'Longitude',
       'TotalPositiveCases'],
      dtype='object')

In [8]:
data.tail()

,SNo,Date,Country,RegionCode,RegionName,ProvinceCode,ProvinceName,ProvinceAbbreviation,Latitude,Longitude,TotalPositiveCases
22912,22912,2020-08-12T17:00:00,ITA,5,Veneto,27,Venezia,VE,45.434905,12.338452,2969
22913,22913,2020-08-12T17:00:00,ITA,5,Veneto,28,Padova,PD,45.406930,11.876087,4383
22914,22914,2020-08-12T17:00:00,ITA,5,Veneto,29,Rovigo,RO,45.071073,11.790070,476
22915,22915,2020-08-12T17:00:00,ITA,5,Veneto,899,Fuori Regione / Provincia Autonoma,NaN,NaN,NaN,316
22916,22916,2020-08-12T17:00:00,ITA,5,Veneto,999,In fase di definizione/aggiornamento,NaN,NaN,NaN,41

In [9]:
data = pd.read_csv(r'G:\my video lecture\projects\cv19.csv')

In [10]:
data.head()

,SNo,Date,Country,RegionCode,RegionName,Latitude,Longitude,HospitalizedPatients,IntensiveCarePatients,TotalHospitalizedPatients,HomeConfinement,CurrentPositiveCases,NewPositiveCases,Recovered,Deaths,TotalPositiveCases,TestsPerformed
0,0,2020-02-24T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,0,0,0,0,0,NaN
1,1,2020-02-24T18:00:00,ITA,17,Basilicata,40.639471,15.805148,0,0,0,0,0,0,0,0,0,NaN
2,2,2020-02-24T18:00:00,ITA,18,Calabria,38.905976,16.594402,0,0,0,0,0,0,0,0,0,NaN
3,3,2020-02-24T18:00:00,ITA,15,Campania,40.839566,14.250850,0,0,0,0,0,0,0,0,0,NaN
4,4,2020-02-24T18:00:00,ITA,8,Emilia-Romagna,44.494367,11.341721,10,2,12,6,18,18,0,0,18,NaN

In [11]:
data.columns

Index(['SNo', 'Date', 'Country', 'RegionCode', 'RegionName', 'Latitude',
       'Longitude', 'HospitalizedPatients', 'IntensiveCarePatients',
       'TotalHospitalizedPatients', 'HomeConfinement', 'CurrentPositiveCases',
       'NewPositiveCases', 'Recovered', 'Deaths', 'TotalPositiveCases',
       'TestsPerformed'],
      dtype='object')

In [12]:
data.tail()

,SNo,Date,Country,RegionCode,RegionName,Latitude,Longitude,HospitalizedPatients,IntensiveCarePatients,TotalHospitalizedPatients,HomeConfinement,CurrentPositiveCases,NewPositiveCases,Recovered,Deaths,TotalPositiveCases,TestsPerformed
3586,3586,2020-08-12T17:00:00,ITA,19,Sicilia,38.115697,13.362357,43,6,49,513,562,29,2757,284,3603,233597.0
3587,3587,2020-08-12T17:00:00,ITA,9,Toscana,43.769231,11.255889,15,3,18,545,563,33,9007,1137,10707,300764.0
3588,3588,2020-08-12T17:00:00,ITA,10,Umbria,43.106758,12.388247,9,0,9,48,57,6,1380,80,1517,82645.0
3589,3589,2020-08-12T17:00:00,ITA,2,Valle d'Aosta,45.737503,7.320149,5,0,5,10,15,0,1056,146,1217,16342.0
3590,3590,2020-08-12T17:00:00,ITA,5,Veneto,45.434905,12.338452,33,6,39,1294,1333,60,17376,2092,20801,516131.0

In [13]:
data.describe()

,SNo,RegionCode,Latitude,Longitude,HospitalizedPatients,IntensiveCarePatients,TotalHospitalizedPatients,HomeConfinement,CurrentPositiveCases,NewPositiveCases,Recovered,Deaths,TotalPositiveCases,TestsPerformed
count,3591.000000,3591.000000,3591.000000,3591.000000,3591.000000,3591.000000,3591.000000,3591.000000,3591.000000,3591.000000,3591.000000,3591.000000,3591.000000,2436.000000
mean,1795.000000,11.857143,43.046293,12.225955,460.956280,52.086884,513.043163,1594.043999,2107.087162,70.115288,5260.510721,1189.205792,8556.803676,132636.411741
std,1036.776736,6.274672,2.489127,2.659318,1347.956483,142.930582,1485.726449,3623.476180,4859.194678,203.748395,11177.130031,2963.299072,17012.733130,140344.068319
min,0.000000,1.000000,38.115697,7.320149,0.000000,0.000000,0.000000,0.000000,0.000000,-229.000000,0.000000,0.000000,0.000000,3482.000000
25%,897.500000,7.000000,41.125596,11.121231,10.000000,0.000000,11.000000,70.500000,87.000000,1.000000,211.000000,58.000000,1042.500000,42369.250000
50%,1795.000000,12.000000,43.616760,12.388247,60.000000,6.000000,68.000000,330.000000,410.000000,9.000000,1324.000000,287.000000,3114.000000,80360.000000
75%,2692.500000,17.000000,45.434905,13.768136,283.000000,38.000000,319.000000,1345.000000,1712.500000,49.000000,4198.500000,862.500000,7285.500000,175111.000000
max,3590.000000,22.000000,46.499335,16.867367,12077.000000,1381.000000,13328.000000,30382.000000,37307.000000,3251.000000,74700.000000,16833.000000,97054.000000,829237.000000

In [16]:
data.columns

Index(['SNo', 'Date', 'Country', 'RegionCode', 'RegionName', 'Latitude',
       'Longitude', 'HospitalizedPatients', 'IntensiveCarePatients',
       'TotalHospitalizedPatients', 'HomeConfinement', 'CurrentPositiveCases',
       'NewPositiveCases', 'Recovered', 'Deaths', 'TotalPositiveCases',
       'TestsPerformed'],
      dtype='object')

# relating the variables with scatterplots

In [17]:
sns.relplot(x='Recovered',y='CurrentPositiveCases',data = data)

NameError: name 'sns' is not defined

In [10]:
seaborn.relplot(x='Recovered',y='CurrentPositiveCases',data = data)

NameError: name 'seaborn' is not defined

In [11]:
sns.relplot(x='Recovered',y='CurrentPositiveCases',data = data)

NameError: name 'sns' is not defined